config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts do
    member do
      get :pledge
      post :post_pledge
    end
  end

  root 'home#index'
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :amount, numericality: { integer_only: true, greater_than: 0 }
  after_commit do |pledge|
    pledge.post.update_columns pledged_amount: pledge.post.pledges.sum(:amount)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, styles: {
      large: "600x600>",
      medium: "300x300>",
      thumb: "150x150#"
    },
    default_url: -> (attachment) {
      ActionController::Base.helpers.asset_path('no-image.png')
    }

  belongs_to :user
  has_many :pledges

  validates :amount, numericality: { integer_only: true, greater_than: 0 }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :title, :description, :amount, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :pledge, :post_pledge, :update, :destroy]
  before_action :authorize_post_owner, only: [:edit, :update, :destroy]
  before_action :ensure_posting_pledge_once_only, only: [:pledge, :post_pledge]

  def post_owner
    unless @post.user == current_user
      flash[:notice] = 'Access denied as you are not owner of this Post'
      redirect_to posts_path
    end
  end

  def index
    @posts = Post.limit(10).order("created_at DESC")
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Successfully updated project'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Successfully removed project'
  end

  def pledge
    @pledge = @post.pledges.build
  end

  def post_pledge
    @pledge = Pledge.new post_pledge_params
    @pledge.post = @post
    @pledge.user = current_user
    if @pledge.save
      redirect_to @post, notice: 'Thank you'
    else
      render :pledge
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :amount, :image)
  end

  def post_pledge_params
    params.require(:pledge).permit(:amount)
  end

  def ensure_posting_pledge_once_only
    if Pledge.where(user_id: current_user.id, post_id: @post.id).exists?
      redirect_to @post, alert: 'You already posted a pledge to the project'
    end
  end

  def authorize_post_owner
    unless @post.user == current_user
      flash[:notice] = 'Access denied as you are not owner of this Post'
      redirect_to posts_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private 

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_upadate_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for_flash_type(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-danger',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def user_allowed
  		user_signed_in? && (current_user.id == @job.user_id)
	end
end

app/views/home/index.html.erb
  <div class="backgroundpic">
    <div class="containerBlock">
      <div class="mainText">
        <h1>Make Your Own Project</h1>
        <% if user_signed_in? %>
            <a class="button-mainText" href="<%= new_post_path %>">Get started</a>
        <% else %>
            <p>You have to <a href="<%= new_user_session_path %>">Sign in</a> to  pledge</p>
        <% end %>
      </div>
    </div>
  </div>

<!-- bottom bar -->

  <div class="supportingBlock">
    <div class="containerBlock">

      <div class="colBlock">
        <img src="https://image.freepik.com/free-icon/person-reading-book_318-29353.jpg">
        <h2>Study</h2>
        <p>Study And Plan On How To Make Your Project</p>
      </div>

      <div class="colBlock">
        <img src="http://image.flaticon.com/icons/svg/50/50711.svg">
        <h2>Demonstrate </h2>
        <p>Prepare Your project And Present It To Other People.</p>
      </div>

      <div class="colBlock">
        <img src="https://viewfromthegravytrain.files.wordpress.com/2014/01/icon_14894.png">
        <h2>Kick-Start</h2>
        <p> Use The Funding To Achieve Your Plans </p>
      </div>

    </div>
    <div class="clearfix"></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <link href="https://fonts.googleapis.com/css?family=Raleway:400, 600" rel="stylesheet">
      <title>Forum</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <!--  navigation bar -->
        <div class="headerBlock">
            <div class="containerBlock">
                <ul class="navBlock">
                    <li><a class="active" href="<%= root_path %>">Home</a></li>
                    <li><a href="<%= posts_path %>">Newest</a></li>
                    <% if user_signed_in? %>
                        <li style="float:right">
                            <a href="<%= destroy_user_session_path %>">Hi <%= current_user.name %>, Logout</a>
                        </li>
                    <% else %>
                        <li style="float:right"><a href="<%= new_user_session_path %>">Sign in</a></li>
                    <% end %>
                </ul>
          </div>
        </div>
        <div class="contentBlock">
            <%= render 'shared/flash_messages' %>
            <%= yield %>
        </div>
        <!-- footer -->
        <footer>
            <div class="footerBlock">
                <div class="containerBlock">
                </div>
            </div>
        </footer>
    </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title, label: 'Enter Your Title' %>
  <%= f.input :description, label: 'Enter description for your project', input_html: { rows: 5 } %>
  <%= f.input :amount, label: 'Enter how much do you need' %>
  <%= f.input :image %>
  <button type="submit" class="btn btn-primary btn-block">ENTER</button>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-20">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Edit Your Project</h3>
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
 <div class="container newest">
    <div class="postsBlock">
        <h2 class="postTitle">Newest posts</h2>
        <div class="row mb-30 mt-20 pa-10 project">
            <% @posts.each do |post| %>
                <div class="col-md-4 text-center">
                    <a href="<%= post_path(post) %>">
                    <img src="<%= post.image.url(:large) %>" class="project-thumb" alt="Responsive image">
                    </a>
                    <h3><a href="<%= post_path(post) %>"><%= post.title %></a></h3>
                    <p><%= truncate(post.description, length: 50) %></p>
                    <h4>Amount to Goal: $<%= post.pledged_amount %></h4>

                    <br>
                    <% if (post.pledged_amount >= post.amount) %>
                        <h4 class="text-success">Pledge reached!</h4>
                    <% else %>
                         <% if user_signed_in? %>
                        <a href="<%= pledge_post_path(post) %>" class="btn btn-success btn-lg">Pledge</a>
                        <% else %>
                        <p>You have to <a href="<%= new_user_session_path %>">Sign in</a> to  pledge</p>
                        <% end %>
                    <% end %>
                    <br>
                    <br>
                    <% if current_user == post.user.id %>
                    <%= link_to "Edit", edit_post_path(post) %>
                    <%= link_to "Remove", post, method: :delete, data: {confirm: "Are you sure?"}, class: "text-danger" %>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-20">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Create New Project</h3>
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/pledge.html.erb
<div class="container">
    <div class="postsBlock">
        <div class="row mb-30 mt-20">
            <div class="col-md-6 text-center">
                <div class="ma-10">
                    <img src="<%= @post.image.url(:large) %>" class="img-responsive">
                    <h3><a href="<%= post_path(@post) %>"><%= @post.title %></a></h3>
                    <p><%= @post.description %></p>
                    <h4>Pledge Amount: $<%= @post.pledged_amount %></h4>
                    <br>
                </div>
            </div>
            <div class="col-md-6">
                <div class="ma-10">
                    <h3>Enter amount:</h3>
                    <%= simple_form_for @pledge, method: 'POST', url: post_pledge_post_path do |f| %>
                        <%= f.input :amount %>
                        <button type="submit" class="btn btn-primary btn-block">ENTER</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="postsBlock">
        <div class="row mb-30 mt-20">
            <div class="col-md-12 text-center mt-20">
                <img src="<%= @post.image.url (:large) %>">
                <h3><%= @post.title %></h3>
                <p><%= @post.description %></p>
                <h4>Amount to Goal: $<%= @post.amount - @post.pledged_amount %></h4>
                <br>
                    <% if (@post.pledged_amount >= @post.amount) %>
                        <h4 class="text-success">Pledge reached!</h4>
                    <% else %>
                        <% if user_signed_in? %>
                        <a href="<%= pledge_post_path(@post) %>" class="btn btn-success btn-lg">Pledge</a>
                        <% else %>
                        <p>You have to <a href="<%= new_user_session_path %>">Sign in</a> to  pledge</p>
                        <% end %>
                    <% end %>
                <br>
                <br>
                <% if current_user == @post.user.id %>
                <%= link_to "Edit", edit_post_path(@post) %>
                <%= link_to "Remove", @post, method: :delete, data: {confirm: "Are you sure?"}, class: "text-danger" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash %>
    <% flash.each do |type, message| %>
        <% if %w(alert notice info error).include? type %>
            <div class="alert alert-dismissible fade in <%= alert_class_for_flash_type(type) %>">
            <button class="close" data-dismiss="alert" type="button">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <%= message.html_safe %>
            </div>
        <% end %>
    <% end %>
<% end %>